/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ezsMN96Be8V
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Entrypage() {
  return (
    <div className="flex min-h-[100dvh] flex-col">
      <header className="w-full bg-gray-500 from-primary to-secondary py-12 md:py-20 lg:py-24">
        <div className="container mx-auto px-4 md:px-6 lg:px-8">
          <div className="mx-auto max-w-3xl text-center">
            <h1 className="text-4xl font-bold tracking-tight text-primary-foreground sm:text-5xl lg:text-6xl">
              Unlock the Best of the Web
            </h1>
            <p className="mt-4 text-lg text-muted-foreground sm:mt-6">
              Discover the top free resources for learning, productivity, and creativity. Elevate your digital
              experience.
            </p>
            <div className="mt-8 sm:mt-10">
              <Link
                href="/content"
                className="inline-flex items-center rounded-md bg-primary px-5 py-3 text-base font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                prefetch={false}
              >
                Explore Now
              </Link>
            </div>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="py-12 md:py-16 lg:py-20 bg-muted">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <div className="mx-auto max-w-3xl text-center">
              <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Free Online Courses</h2>
              <p className="mt-4 text-muted-foreground sm:mt-6">
                Expand your knowledge with high-quality courses from top universities and industry experts.
              </p>
              <div className="mt-8 sm:mt-10">
                <Link
                  href="#"
                  className="inline-flex items-center rounded-md border border-transparent bg-secondary px-5 py-3 text-base font-medium text-secondary-foreground shadow-sm transition-colors hover:bg-secondary/90 focus:outline-none focus:ring-2 focus:ring-secondary focus:ring-offset-2"
                  prefetch={false}
                >
                  Explore Courses
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-20">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <div className="mx-auto max-w-3xl text-center">
              <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Free Software Tools</h2>
              <p className="mt-4 text-muted-foreground sm:mt-6">
                Boost your productivity with a curated selection of the best free software tools.
              </p>
              <div className="mt-8 sm:mt-10">
                <Link
                  href="#"
                  className="inline-flex items-center rounded-md border border-transparent bg-primary px-5 py-3 text-base font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                  prefetch={false}
                >
                  Explore Tools
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-20 bg-muted">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <div className="mx-auto max-w-3xl text-center">
              <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Free Design Assets</h2>
              <p className="mt-4 text-muted-foreground sm:mt-6">
                Elevate your designs with a vast collection of free icons, templates, and graphics.
              </p>
              <div className="mt-8 sm:mt-10">
                <Link
                  href="#"
                  className="inline-flex items-center rounded-md border border-transparent bg-secondary px-5 py-3 text-base font-medium text-secondary-foreground shadow-sm transition-colors hover:bg-secondary/90 focus:outline-none focus:ring-2 focus:ring-secondary focus:ring-offset-2"
                  prefetch={false}
                >
                  Explore Assets
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-20">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <div className="mx-auto max-w-3xl text-center">
              <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
                Free Educational Content
              </h2>
              <p className="mt-4 text-muted-foreground sm:mt-6">
                Expand your mind with a vast library of free educational articles, tutorials, and resources.
              </p>
              <div className="mt-8 sm:mt-10">
                <Link
                  href="#"
                  className="inline-flex items-center rounded-md border border-transparent bg-primary px-5 py-3 text-base font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                  prefetch={false}
                >
                  Explore Content
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
