/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6R3LZSGw2NI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"
import { Card, CardHeader, CardTitle, CardContent } from "@ui/components/ui/card"
import Link from "next/link"
import InfoCard from "./InfoCard"
import { useState } from "react"

type TopicContentPageProps = {
    topic: string
}

export function TopicContentPage({topic}:TopicContentPageProps) {
    
    const podcastItems = [
        {
          href: "#",
          label: "The Changelog",
          description: "A weekly podcast that explores the world of open source software."
        },
        {
          href: "#",
          label: "JavaScript Jabber",
          description: "A podcast about JavaScript, front-end development, and more."
        },
        {
          href: "#",
          label: "The Syntax Podcast",
          description: "A podcast about web development, JavaScript, and everything in between."
        },
        {
          href: "#",
          label: "Full Stack Radio",
          description: "A podcast for developers interested in building great software products."
        }
      ];
  return (
    <div className="flex flex-col">
      <section className="w-full py-6 md:py-12 lg:py-16">
        <div className="container grid gap-10 px-4 md:px-6 lg:grid-cols-2 lg:gap-16">
            <div className="space-y-4">
            
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
                Mastering the Art of {topic}
            </h1>
            <p className="max-w-[700px] text-muted-foreground md:text-xl/relaxed">
                Dive deep into the world of {topic} and unlock your full potential as a developer. From the
                fundamentals to advanced techniques, this page is your comprehensive guide to mastering the craft.
            </p>
            </div>
            <img
            src="/placeholder.svg"
            width={800}
            height={600}
            alt={topic}
            className="mx-auto aspect-video overflow-hidden rounded-xl object-cover"
            />
        </div>
        </section>

      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container space-y-12 px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Explore {topic} Resources
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Dive into a curated collection of podcasts, YouTube channels, books, audiobooks, blogs, research papers,
                and courses to enhance your web development journey.
              </p>
            </div>
          </div>
          <div className="grid gap-8 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            <InfoCard 
                icon={<PodcastIcon className="h-5 w-5" />}
                title="Podcasts "
                items={podcastItems}
            />
            <InfoCard 
                icon={<YoutubeIcon className="h-5 w-5" />}
                title="Youtube Resources"
                items={podcastItems}
            />
            <InfoCard 
                icon={<BookIcon className="h-5 w-5" />}
                title="Books"
                items={podcastItems}
            />
            <InfoCard 
                icon={<HeadphonesIcon className="h-5 w-5" />}
                title="Songs"
                items={podcastItems}
            />
            <InfoCard 
                icon={<SchoolIcon className="h-5 w-5" />}
                title="Courses"
                items={podcastItems}
            />
            <InfoCard 
                icon={<BookmarkIcon className="h-5 w-5" />}
                title="Blogs"
                items={podcastItems}
            />
            <InfoCard 
                icon={<CodeIcon className="h-5 w-5" />}
                title="Websites"
                items={podcastItems}
            />
            
          </div>
        </div>
      </section>
    </div>
  )
}

function BookIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}


function BookmarkIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z" />
    </svg>
  )
}


function CodeIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}


function HeadphonesIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 14h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-7a9 9 0 0 1 18 0v7a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3" />
    </svg>
  )
}


function PodcastIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16.85 18.58a9 9 0 1 0-9.7 0" />
      <path d="M8 14a5 5 0 1 1 8 0" />
      <circle cx="12" cy="11" r="1" />
      <path d="M13 17a1 1 0 1 0-2 0l.5 4.5a.5.5 0 1 0 1 0Z" />
    </svg>
  )
}


function SchoolIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14 22v-4a2 2 0 1 0-4 0v4" />
      <path d="m18 10 4 2v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-8l4-2" />
      <path d="M18 5v17" />
      <path d="m4 6 8-4 8 4" />
      <path d="M6 5v17" />
      <circle cx="12" cy="9" r="2" />
    </svg>
  )
}


function YoutubeIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  )
}
